#+ summary: Get phosphorylated proteins in the cytoplasm
#+ endpoint_in_url: False
#+ enumerate:
#+   - term:
#+     - http://nextprot.org/rdf/terminology/KW-0597
#+   - location:
#+     - http://nextprot.org/rdf/terminology/GO_0005737


PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX : <http://nextprot.org/rdf#>
PREFIX cv: <http://nextprot.org/rdf/terminology/>

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :keyword / :term ?_term_iri .
  ?iso :cellularComponent ?loc .
  ?loc :term /:childOf ?_location_iri .
  filter not exists {?loc  :negativeEvidence ?negev} # No negative localization evidence
}
